### ISSUE TITLE
Build-ed application cannot start on Windows

### ISSUE THREAD

**Issue by sectorogo** [ingvar1995/Camelot#1]
It builds successfully on Windows but the application does not start at all. Usind SDK 3.1.201 (x64) on Windows 10 x64 1909.

Btw, very nice project. I hope to see more features added and more modern look like acrylic blurry background with SetWindowCompositionAttribute.

**Comment by ingvar1995** [comment]
Hello! Thanks for your feedback. Windows version should work now in master branch. UI is still far from mockups and currently it's even completely broken. I wanna finish basic set of features first and fix UI right after that. I like your idea about UI but not sure that Avalonia supports semi-transparent blurry backgrounds. As longer I'm Linux user it's a bit problematic to test this feature for me :smile:

**Comment by sectorogo** [comment]
It should be possible in c#.

https://gist.github.com/riverar/fd6525579d6bbafc6e48

I am waiting for some time to see some modern UI file manager. All the current are stuck with old UIs from 90s.

**Comment by ingvar1995** [comment]
I'm closing this because master branch works on windows now. If you have any suggestions regarding UI please open separate issue/issues for them
